# Generated by Django 2.1.2 on 2018-10-25 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('DonationID', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionID', models.CharField(max_length=50, unique=True, verbose_name='Transaction ID')),
                ('Amount', models.IntegerField()),
                ('Status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Event', models.AutoField(primary_key=True, serialize=False)),
                ('EventName', models.CharField(max_length=50, verbose_name='Event Name')),
                ('Description', models.CharField(max_length=1000, verbose_name='Event Description')),
                ('Image', models.ImageField(height_field=50, upload_to=None, width_field=50)),
                ('Organiser1', models.CharField(max_length=50, verbose_name='Organisers1 Name')),
                ('Organiser2', models.CharField(max_length=50, verbose_name='Organisers2 Name')),
                ('Organiser3', models.CharField(max_length=50, verbose_name='Organisers3 Name')),
                ('MobileNo1', models.CharField(max_length=10, verbose_name="Organiser1's Mobile Number")),
                ('MobileNo2', models.CharField(max_length=10, verbose_name="Organiser2's Mobile Number")),
                ('MobileNo3', models.CharField(max_length=10, verbose_name="Organiser3's Mobile Number")),
                ('IsActive', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('FeedbackID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, verbose_name='Name')),
                ('EmailID', models.EmailField(max_length=254, unique=True, verbose_name='Email Id')),
                ('Feedback', models.CharField(max_length=100, verbose_name='Feedback....')),
            ],
        ),
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('NewsFeedID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50, verbose_name='Title')),
                ('Content', models.CharField(max_length=1000, verbose_name='Content')),
                ('Image', models.ImageField(height_field=50, upload_to=None, width_field=50)),
                ('Category', models.CharField(max_length=50, verbose_name='Category')),
                ('CreatedBy', models.CharField(max_length=10, verbose_name='CreatedBy User ID')),
                ('UpdatedBy', models.CharField(max_length=10, null=True, verbose_name='UpdatedBy User ID')),
                ('UpdatedOn', models.DateField(null=True)),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionID', models.CharField(max_length=50, unique=True, verbose_name='Transaction ID')),
                ('Amount', models.IntegerField()),
                ('Status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FName', models.CharField(max_length=50, verbose_name="User's First Name")),
                ('LName', models.CharField(max_length=50, verbose_name="User's Last Name")),
                ('EmailID', models.EmailField(max_length=254, unique=True, verbose_name="User's Email Id")),
                ('Password', models.CharField(max_length=50, verbose_name="User's Password")),
                ('MobileNo', models.CharField(max_length=10, verbose_name="User's Mobile Number")),
                ('Type', models.CharField(max_length=50, verbose_name="User's Type")),
                ('IsLoggedIn', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='EmailID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.User'),
        ),
        migrations.AddField(
            model_name='payment',
            name='EventID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.Events'),
        ),
        migrations.AddField(
            model_name='donation',
            name='EmailID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.User'),
        ),
    ]
