# Generated by Django 2.1.2 on 2018-10-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Feedback',
            field=models.CharField(max_length=1000, verbose_name='Feedback....'),
        ),
    ]
