# Generated by Django 2.1.2 on 2018-10-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_auto_20181027_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='EmailID',
            field=models.EmailField(max_length=254, verbose_name='Email Id'),
        ),
    ]
